# name: Build and Deploy Docker Image

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # маркер артифакт по бланку
#       - name: Download build completion marker
#         uses: actions/download-artifact@v4
#         with:
#           name: build-completion
#           path: /tmp/build-completion/marker-file  # Ensure this path matches the upload path

#       # Шаги для сборки бинарных файлов
#       - uses: actions/checkout@v2
      
#       # Логинимся в Docker Hub
#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       # Сборка Docker-образа
#       - name: Build Docker image
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/http-server:latest .

#       # Публикация Docker-образа на Docker Hub
#       - name: Push Docker image
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/http-server:latest

#       # Тесты сервера
#       - name: Run server tests in Docker container
#         run: |
#           docker run -d -p 7777:7777 --name test-server ${{ secrets.DOCKER_USERNAME }}/http-server:latest
#           sleep 5  # ожидание для запуска сервера
#           curl http://localhost:7777/users
#           docker stop test-server
#           docker rm test-server